let menuJson = [
    {id:1, name:'Simples Burger', img:'images/Simples Burger.png', price:22.0, description:'Pão, 1 Carne de 140g e Queijo Cheddar.', categoria:'Artesanais'},
    {id:2, name:'Classic', img:'images/Classic.png', price:28.0, description:'Pão, 1 Carne de 140g, Queijo Cheddar, Alface, Tomate, Cebola Roxa, Maionese e Ketchup.', categoria:'Artesanais'},
    {id:3, name:'Stake House', img:'images/Stake House.png', price:28.0, description:'Pão, 1 Carne de 140g, Queijo Cheddar, Crispy Onion, Alface, Tomate, Molho Barbecue e Molho da Casa.', categoria:'Artesanais'},     
    {id:4, name:'Nordestino', img:'images/Nordestino.png', price:36.0, description:'Pão Australiano, Hambúrguer de 140g, Bacon, Queijo Coalho, Queijo Cheddar e Molho da Casa.', categoria:'Artesanais'},
    {id:5, name:'Nordestino Duplo', img:'images/Nordestino Duplo.png', price:44.0, description:'Pão Australiano, 2 Hambúrgueres de 140g, Bacon, Queijo Coalho, Queijo Cheddar e Molho da Casa.', categoria:'Artesanais'},
    {id:6, name:'Monster 1.0', img:'images/Monster 1.0.png', price:28.0, description:'Pão, 1 Carne de 140g, Queijo Cheddar, Bacon e Molho da Casa.', categoria:'Artesanais'},
    {id:7, name:'Monster 2.0', img:'images/Monster Duplo.png', price:38.0, description:'Pão, 2 Carnes de 140g, Queijo Cheddar, Bacon e Molho da Casa.', categoria:'Artesanais'},
    {id:8, name:'Monster Burger', img:'images/Monster Burger.png', price:48.0, description:'Pão, 3 Carnes de 140g, Queijo Cheddar, Bacon e Molho da Casa.', categoria:'Artesanais'},
    {id:9, name:'Cheddar', img:'images/Cheddar.png', price:28.0, description:'Pão, 1 Carne de 140g, Cheddar, Bacon e Molho da Casa.', categoria:'Artesanais'},
    {id:10, name:'Cheddar Duplo', img:'images/Cheddar Duplo.png', price:38.0, description:'Pão, 2 Carnes de 140g, Cheddar, Bacon e Molho da Casa.', categoria:'Artesanais'},
    {id:11, name:'Onion Burger', img:'images/Onion Burger.png', price:30.0, description:'Pão, 1 Carne de 140g, Queijo Cheddar, Onion Rings, Molho Barbecue e Molho da Casa.', categoria:'Artesanais'},
    {id:12, name:'Onion Duplo', img:'images/Onion Duplo.png', price:40.0, description:'Pão, 2 Carnes de 140g, Queijo Cheddar, Onion Rings, Molho Barbecue e Molho da Casa.', categoria:'Artesanais'},
    {id:13, name:'Onion Especial', img:'images/OnionEspecial.png', price:36.0, description:'Pão Australiano, 1 Carne de 140g, Creme Cheddar, Onion Rings, Bacon e Molho da Casa.', categoria:'Artesanais'},
    {id:14, name:'Smach Salada', img:'images/Smach Salada.png', price:22.0, description:'Pão Brioche, 1 Carne de 70g, Maionese, Alface, Tomate, Cebola Roxa e Ketchup.', categoria:'Artesanais'},
    {id:15, name:'Smach Salada Duplo', img:'images/Smach salada duplo.png', price:26.0, description:'Pão Brioche, 2 Carnes de 70g, Maionese, Alface, Tomate, Cebola Roxa e Ketchup.', categoria:'Artesanais'},
    {id:16, name:'Smach Burger', img:'images/Smach Burger.png', price:22.0, description:'Pão Brioche, 1 Carne de 70g, Bacon e Molho da Casa.', categoria:'Artesanais'},
    {id:17, name:'Smach Burger Duplo', img:'images/Smach Burger Duplo.png', price:26.0, description:'Pão Brioche, 2 Carnes de 70g, Bacon e Molho da Casa.', categoria:'Artesanais'},
    {id:18, name:'Smach Burger Triplo', img:'images/Smach Burger Triplo.png', price:30.0, description:'Pão Brioche, 3 Carnes de 70g, Bacon e Molho da Casa.', categoria:'Artesanais'},
    {id:19, name:'Combo Smash Solteiro', img:'images/Combo Smash Solteiro.png', price:32.0, description:'1 Smash Salada, Batata com Cheddar e 1 Guaraná Antártica 269ml.', categoria:'Combos'},
    {id:20, name:'Combo Smash Casal', img:'images/Combo Smash Casal.png', price:60.0, description:'2 Smash Salada, Batata com Cheddar e 2 Guaraná Antártica 269ml.', categoria:'Combos'},
    {id:21, name:'Combo Solteiro', img:'images/Combo Solteiro.png', price:40.0, description:'1 Classic, Batata (Cheddar, Bacon e Calabresa) e 1 Guaraná Antártica 269ml.', categoria:'Combos'},
    {id:22, name:'Combo Casal', img:'images/Combo Casal.png', price:85.0, description:'2 Classics, Batata (Cheddar, Bacon e Calabresa) 2 Guaraná Antártica 269ml.', categoria:'Combos'},
    {id:23, name:'Combo Família', img:'images/Combo Família.png', price:160.0, description:'4 Classics, Batata (Cheddar, Bacon e Calabresa) e 1 Dolly 2L.', categoria:'Combos'},
    {id:24, name:'Porção de Onions Rings', img:'images/Onions Rings.png', price:25.0, description:'Onions Rings, Cheddar e Bacon.', categoria:'Porções'},
    {id:25, name:'Batata Crinkle', img:'images/Batata Crinkle.png', price:22.0, description:'Batata Crinkle.', categoria:'Porções'},
    {id:26, name:'Batata Crinkle (Cheddar e Bacon)', img:'images/Batata Crinkle (Cheddar e Bacon).png', price:35.0, description:'Batata Crinkle, cheddar e bacon.', categoria:'Porções'},
    {id:27, name:'Batata P', img:'images/Batata P.png', price:28.0, description:'Batata, cheddar, bacon e calabresa.', categoria:'Porções'},
    {id:28, name:'Batata M', img:'images/Batata M.png', price:45.0, description:'Batata, cheddar, bacon e calabresa.', categoria:'Porções'},
    {id:29, name:'Fanta Laranja 350ml', img:'images/Fanta Laranja 350ml.png', price:5.0, description:'Refrigerante Fanta Laranja 350ml', categoria:'Bebidas'},
    {id:30, name:'Fanta Uva 350ml', img:'images/Fanta Uva 350ml.png', price:5.0, description:'Refrigerante Fanta Uva 350ml', categoria:'Bebidas'},
    {id:31, name:'Guaraná Antártica 350ml', img:'images/Guaraná Antártica 350ml.png', price:5.0, description:'Refrigerante Guaraná Antártica 350ml', categoria:'Bebidas'},
    {id:32, name:'Coca-Cola 350ml', img:'images/Coca-Cola 350ml.png', price:6.0, description:'Refrigerante Coca-Cola 350ml', categoria:'Bebidas'},
    {id:33, name:'Coca-Cola Zero 350ml', img:'images/Coca-Cola Zero 350ml.png', price:6.0, description:'Refrigerante Coca-Cola Zero 350ml', categoria:'Bebidas'},
    {id:34, name:'Coca-Cola 1,5L', img:'images/Coca-Cola 1-5L.png', price:13.0, description:'Refrigerante Coca-Cola 1,5L', categoria:'Bebidas'},
    {id:35, name:'Coca-Cola 2L', img:'images/Coca-Cola 2l.png', price:16.0, description:'Refrigerante Coca-Cola 2l', categoria:'Bebidas'},
    {id:36, name:'Coca-Cola Zero 2L', img:'images/Coca-Cola Zero 2l.png', price:16.0, description:'Refrigerante Coca-Cola Zero 2l', categoria:'Bebidas'},
    {id:37, name:'Fanta Laranja 2L', img:'images/Fanta Laranja 2l.png', price:13.0, description:'Refrigerante Fanta Laranja 2l', categoria:'Bebidas'},
    {id:38, name:'Fanta Uva 2L', img:'images/Fanta Uva 2l.png', price:13.0, description:'Refrigerante Fanta Uva 2l', categoria:'Bebidas'},
    {id:39, name:'Guaraná Antártica 2L', img:'images/Guaraná Antártica 2l.png', price:13.0, description:'Refrigerante Guaraná Antártica 2l', categoria:'Bebidas'},
    {id:40, name:'Pepsi 2L', img:'images/Pepsi 2L.png', price:13.0, description:'Refrigerante Pepsi 2L', categoria:'Bebidas'},
    {id:41, name:'Sukita Laranja 2L', img:'images/Sukita Laranja 2L.png', price:10.0, description:'Refrigerante Sukita Laranja 2L', categoria:'Bebidas'},
    {id:42, name:'Sukita Uva 2L', img:'images/Sukita Uva 2L.png', price:10.0, description:'Refrigerante Sukita Uva 2L', categoria:'Bebidas'},
    {id:43, name:'Dolly 2L', img:'images/Dolly 2L.png', price:9.0, description:'Refrigerante Dolly 2L', categoria:'Bebidas'},
    {id:44, name:'Sucos 1L', img:'images/Sucos1l.png', price:10.0, description:'Sucos de 1L', categoria:'Bebidas'},
    {id:45, name:'Bombom Oreo e Nutella', img:'images/Oreo e Nutella.png', price:10.0, description:'Bombom Gourmet de Oreo e Nutella.', categoria:'Sobremesa'},
    {id:46, name:'Bombom Ninho e Nutella', img:'images/Ninho e Nutella.png', price:10.0, description:'Bombom Gourmet de Ninho e Nutella.', categoria:'Sobremesa'}
];